### ISSUE TITLE
Water is generated incorrectly

### ISSUE THREAD

**Issue by waleed177** [jjmontesl/ddd#3]
Water at @43.3835268,-8.4097834,2a,35y,285.7h,76.50t is floating
![image](https://user-images.githubusercontent.com/33373452/130951725-fa118f1a-18fe-47f4-8a9c-916f9a8be0b6.png)

Link:
https://3dsmaps.com/3d/@43.3835268,-8.4097834,2a,35y,285.7h,76.50t

**Comment by jjmontesl** [comment]
This is related to a more general issue with elevation and layer management. Since this is still all work in progress I'm closing this issue as it's very likely to have been dealt with or changed heavily.
